version: '3'

services:
  caddy:
    image: abiosoft/caddy:latest
    volumes:
      - ./Caddyfile.dev:/etc/Caddyfile
    ports:
      - 2015:2015
    links:
      - api
      # - web

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/src/episodic-api
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=3927
      - DATABASE_URL=postgres://postgres:super_secret_password@db/episodic
    links:
      - db
    command: cargo run

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./web:/usr/src/episodic-web
  #   command: cargo web start --host=0.0.0.0 --port=3928

  db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: super_secret_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5439:5432

volumes:
  pgdata: {}
