version: '3'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/src/episodic-api
    environment:
      - ADDRESS=0.0.0.0
      - PORT=3927
      - DATABASE_URL=postgres://postgres:super_secret_password@db/episodic
    # TODO: unexpose the API from host, web only
    ports:
      - 3927:3927
    links:
      - db
    command: cargo watch -x run

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/usr/src/episodic-web
    ports:
      - 3928:3928
    command: cargo web start --host=0.0.0.0 --port=3928

  db:
    image: postgres:9
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: super_secret_password
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pgdata: {}
