version: '3'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/src/episodic
    environment:
      - ADDRESS=0.0.0.0
      - PORT=3927
      - DATABASE_URL=postgres://postgres:super_secret_password@db/episodic
    ports:
      - 3927:3927
    links:
      - db
    command: cargo watch -x run

  # web:
  #   build:
  #     context: web
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/asdf/asdf/asdf

  db:
    image: postgres:9
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: super_secret_password
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pgdata: {}
